# -*- coding: utf-8 -*-
"""Titanic_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ti-oAyUpNbjx04Gjfem9e68tIksiyFKF
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("/content/train_and_test2.csv")

data.head()

data.tail()

data.describe()

data.info()

data.columns

data.nunique()

data.isnull().sum()

data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)

zero_cols = [col for col in data.columns if "zero" in col]
data.drop(columns=zero_cols, inplace=True)

data.head()

data.describe()

import matplotlib.pyplot as plt
plt.figure(figsize=(8,5))
sns.histplot(data["Age"], kde=True)

plt.title("Age Distribution")
plt.show()

"""##Observation

Most passengers were between 20 and 40 years of age. The distribution appears slightly right-skewed, with a small number of elderly passengers and infants.
"""

plt.figure(figsize=(8,5))
sns.histplot(data["Fare"], kde=True)

plt.title("Fare Distribution")
plt.show()

"""##Observation

Fare distribution is highly positively skewed. Most passengers paid low fares, while a few passengers paid exceptionally high fares, creating outliers.
"""

sns.countplot(x="Pclass", data=data)

plt.title("Passenger Class Distribution")
plt.show()

"""##Observation

Third-class passengers represent the largest group in the dataset, indicating that lower-class travel was the most common.
"""

sns.countplot(x="2urvived", data=data)

plt.title("Survival Count")
plt.show()

"""##Observation

Only about 26% of passengers survived, while nearly 74% did not survive the disaster.
"""

sns.countplot(x="Sex",hue="2urvived",data=data)

plt.title("Gender vs Survival")
plt.show()

"""##Observation

Female passengers had a significantly higher survival rate compared to male passengers, suggesting gender played an important role in rescue priority.
"""

sns.countplot( x="Pclass",hue="2urvived",data=data)

plt.title("Pclass vs Survival")
plt.show()

"""##Observation

First-class passengers had a noticeably higher survival rate than second- and third-class passengers.
"""

plt.figure(figsize=(10,6))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap")
plt.show()

"""##Observation

Fare shows a positive relationship with survival, while passenger class shows a negative relationship with survival. Age has a relatively weak correlation with survival.
"""

sns.boxplot(x="2urvived",y="Age",data=data)

plt.show()

"""##Observation

The age distributions of survivors and non-survivors overlap considerably, indicating that age alone was not a strong determinant of survival.
"""

sns.boxplot(x="2urvived",y="Fare",data=data)

plt.show()

"""##Observation

Survivors generally paid higher fares than non-survivors, suggesting passengers with higher ticket classes had better survival chances.
"""

data["FamilySize"] = data["sibsp"] + data["Parch"] + 1

sns.countplot(x="FamilySize", data=data)
plt.title("Family Size Distribution")
plt.show()

"""## Observation

Most passengers traveled either alone or with very small families.
Large family groups were relatively uncommon.
This suggests that solo travel was more frequent among Titanic passengers.
"""